#pragma once

#include "DataStructures.h"
#include "BuildAbsolutePath.h"
#include <string>

typedef enum {
    MATERIAL_AIR,
    //Stone Types
    MATERIAL_COBBLESTONE,
    MATERIAL_DIORITE,
    //dirt like blocks
    MATERIAL_DIRT,
    MATERIAL_GRASS_BLOCK_TOP,
    MATERIAL_GRASS_BLOCK_SIDE,
    MATERIAL_GRASS_BLOCK_SIDE_OV,
    //wood types
    MATERIAL_BIRCH_LOG_SIDE,
    MATERIAL_BIRCH_LOG_TOP,
    MATERIAL_BIRCH_LEAVES,
    MATERIAL_CHESTNUT_LOG_SIDE,
    MATERIAL_CHESTNUT_LOG_TOP,
    MATERIAL_CHESTNUT_LEAVES,

    //new wood + rock materials
    //savanna: eucalyptus
    MATERIAL_EUCALYPTUS_LOG_SIDE,
    MATERIAL_EUCALYPTUS_LOG_TOP,
    MATERIAL_EUCALYPTUS_STRIPPED_LOG_SIDE,
    MATERIAL_EUCALYPTUS_STRIPPED_LOG_TOP,
    MATERIAL_EUCALYPTUS_PLANKS,
    MATERIAL_EUCALYPTUS_LEAVES,
    //baobab
    MATERIAL_BAOBAB_LOG_SIDE,
    MATERIAL_BAOBAB_LOG_TOP,
    MATERIAL_BAOBAB_STRIPPED_LOG_SIDE,
    MATERIAL_BAOBAB_STRIPPED_LOG_TOP,
    MATERIAL_BAOBAB_PLANKS,
    MATERIAL_BAOBAB_LEAVES,
    //acacia
    MATERIAL_ACACIA_LOG_SIDE,
    MATERIAL_ACACIA_LOG_TOP,
    MATERIAL_ACACIA_STRIPPED_LOG_SIDE,
    MATERIAL_ACACIA_STRIPPED_LOG_TOP,
    MATERIAL_ACACIA_PLANKS,
    MATERIAL_ACACIA_LEAVES,
    //oak
    MATERIAL_OAK_LOG_SIDE,
    MATERIAL_OAK_LOG_TOP,
    MATERIAL_OAK_STRIPPED_LOG_SIDE,
    MATERIAL_OAK_STRIPPED_LOG_TOP,
    MATERIAL_OAK_PLANKS,
    MATERIAL_OAK_LEAVES,
    //dark_oak
    MATERIAL_DARK_OAK_LOG_SIDE,
    MATERIAL_DARK_OAK_LOG_TOP,
    MATERIAL_DARK_OAK_STRIPPED_LOG_SIDE,
    MATERIAL_DARK_OAK_STRIPPED_LOG_TOP,
    MATERIAL_DARK_OAK_PLANKS,
    MATERIAL_DARK_OAK_LEAVES,
    //maple
    MATERIAL_MAPLE_LOG_SIDE,
    MATERIAL_MAPLE_LOG_TOP,
    MATERIAL_MAPLE_STRIPPED_LOG_SIDE,
    MATERIAL_MAPLE_STRIPPED_LOG_TOP,
    MATERIAL_MAPLE_PLANKS,
    MATERIAL_MAPLE_LEAVES,
    //beech
    MATERIAL_BEECH_LOG_SIDE,
    MATERIAL_BEECH_LOG_TOP,
    MATERIAL_BEECH_STRIPPED_LOG_SIDE,
    MATERIAL_BEECH_STRIPPED_LOG_TOP,
    MATERIAL_BEECH_PLANKS,
    MATERIAL_BEECH_LEAVES,
    MATERIAL_BIRCH_STRIPPED_LOG_SIDE,
    MATERIAL_BIRCH_STRIPPED_LOG_TOP,
    MATERIAL_BIRCH_PLANKS,
    //hickory
    MATERIAL_HICKORY_LOG_SIDE,
    MATERIAL_HICKORY_LOG_TOP,
    MATERIAL_HICKORY_STRIPPED_LOG_SIDE,
    MATERIAL_HICKORY_STRIPPED_LOG_TOP,
    MATERIAL_HICKORY_PLANKS,
    MATERIAL_HICKORY_LEAVES,
    //spruce
    MATERIAL_SPRUCE_LOG_SIDE,
    MATERIAL_SPRUCE_LOG_TOP,
    MATERIAL_SPRUCE_STRIPPED_LOG_SIDE,
    MATERIAL_SPRUCE_STRIPPED_LOG_TOP,
    MATERIAL_SPRUCE_PLANKS,
    MATERIAL_SPRUCE_LEAVES,
    //pine
    MATERIAL_PINE_LOG_SIDE,
    MATERIAL_PINE_LOG_TOP,
    MATERIAL_PINE_STRIPPED_LOG_SIDE,
    MATERIAL_PINE_STRIPPED_LOG_TOP,
    MATERIAL_PINE_PLANKS,
    MATERIAL_PINE_LEAVES,
    //fir
    MATERIAL_FIR_LOG_SIDE,
    MATERIAL_FIR_LOG_TOP,
    MATERIAL_FIR_STRIPPED_LOG_SIDE,
    MATERIAL_FIR_STRIPPED_LOG_TOP,
    MATERIAL_FIR_PLANKS,
    MATERIAL_FIR_LEAVES,
    //larch
    MATERIAL_LARCH_LOG_SIDE,
    MATERIAL_LARCH_LOG_TOP,
    MATERIAL_LARCH_STRIPPED_LOG_SIDE,
    MATERIAL_LARCH_STRIPPED_LOG_TOP,
    MATERIAL_LARCH_PLANKS,
    MATERIAL_LARCH_LEAVES,
    //kapok
    MATERIAL_KAPOK_LOG_SIDE,
    MATERIAL_KAPOK_LOG_TOP,
    MATERIAL_KAPOK_STRIPPED_LOG_SIDE,
    MATERIAL_KAPOK_STRIPPED_LOG_TOP,
    MATERIAL_KAPOK_PLANKS,
    MATERIAL_KAPOK_LEAVES,
    //rubber_tree
    MATERIAL_RUBBER_TREE_LOG_SIDE,
    MATERIAL_RUBBER_TREE_LOG_TOP,
    MATERIAL_RUBBER_TREE_STRIPPED_LOG_SIDE,
    MATERIAL_RUBBER_TREE_STRIPPED_LOG_TOP,
    MATERIAL_RUBBER_TREE_PLANKS,
    MATERIAL_RUBBER_TREE_LEAVES,
    //mahogany
    MATERIAL_MAHOGANY_LOG_SIDE,
    MATERIAL_MAHOGANY_LOG_TOP,
    MATERIAL_MAHOGANY_STRIPPED_LOG_SIDE,
    MATERIAL_MAHOGANY_STRIPPED_LOG_TOP,
    MATERIAL_MAHOGANY_PLANKS,
    MATERIAL_MAHOGANY_LEAVES,
    //savanna: granite
    MATERIAL_GRANITE,
    MATERIAL_COBBLED_GRANITE,
    //laterite
    MATERIAL_LATERITE,
    MATERIAL_COBBLED_LATERITE,
    //sandstone
    MATERIAL_SANDSTONE,
    MATERIAL_COBBLED_SANDSTONE,
    //limestone
    MATERIAL_LIMESTONE,
    MATERIAL_COBBLED_LIMESTONE,
    //shale
    MATERIAL_SHALE,
    MATERIAL_COBBLED_SHALE,
    //slate
    MATERIAL_SLATE,
    MATERIAL_COBBLED_SLATE,
    //gneiss
    MATERIAL_GNEISS,
    MATERIAL_COBBLED_GNEISS,
    //schist
    MATERIAL_SCHIST,
    MATERIAL_COBBLED_SCHIST,
    //andesite
    MATERIAL_ANDESITE,
    MATERIAL_COBBLED_ANDESITE,
    //obsidian
    MATERIAL_OBSIDIAN,
    MATERIAL_COBBLED_OBSIDIAN,
    //pumice
    MATERIAL_PUMICE,
    MATERIAL_COBBLED_PUMICE,
    //tuff
    MATERIAL_TUFF,
    MATERIAL_COBBLED_TUFF,
    //scoria
    MATERIAL_SCORIA,
    MATERIAL_COBBLED_SCORIA,
    MATERIAL_COUNT //ALWAYS LAST!!
}Material;

struct ModelFace {
    Material material;
    int overlayMaterial = -1;   // -1 = no overlay
};

const char* materialTextureFile(Material material);

// "COBBLESTONE" -> MATERIAL_COBBLESTONE etc. (enum name minus the MATERIAL_
// prefix). Returns MATERIAL_COUNT for unknown names — callers must check.
// Used by the JSON block-definition loader.
Material materialFromName(const std::string& name);

bool UploadTextureArrayLayer(
    SDL_GPUDevice* gpu,
    SDL_GPUTexture* textureArray,
    const char* filePath,
    const char* fileName,
    Material material
);

bool UploadTextureArrayLayers(
    SDL_GPUDevice* gpu,
    SDL_GPUTexture* textureArray
);

